"""Manage project files, Lean packages and matrix datasets."""

from __future__ import annotations

import json
import csv
from pathlib import Path
from typing import Any


class FileManager:
    """Lightweight file manager for project artifacts."""

    def __init__(self, base_dir: str = ".") -> None:
        self.base = Path(base_dir)
        self.base.mkdir(parents=True, exist_ok=True)

    def _resolve(self, name: str) -> Path:
        p = Path(name)
        return p if p.is_absolute() else self.base / p

    def write_text(self, name: str, content: str) -> str:
        path = self._resolve(name)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return str(path.resolve())

    def read_text(self, name: str) -> str:
        return self._resolve(name).read_text(encoding="utf-8")

    def write_json(self, name: str, data: Any) -> str:
        return self.write_text(name, json.dumps(data, indent=2, default=str))

    def read_json(self, name: str) -> Any:
        return json.loads(self.read_text(name))

    def write_csv(self, name: str, rows: list[list[Any]]) -> str:
        path = self._resolve(name)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerows(rows)
        return str(path.resolve())

    def read_csv(self, name: str) -> list[list[str]]:
        path = self._resolve(name)
        with path.open(newline="", encoding="utf-8") as f:
            return [row for row in csv.reader(f)]

    def list_files(self, subdir: str = ".") -> list[str]:
        d = self._resolve(subdir)
        if not d.exists():
            return []
        return [str(p.relative_to(self.base)) for p in d.rglob("*") if p.is_file()]

    def exists(self, name: str) -> bool:
        return self._resolve(name).exists()

    def delete(self, name: str) -> bool:
        p = self._resolve(name)
        if p.exists():
            p.unlink()
            return True
        return False


# --- Lean package scaffolding ---------------------------------------
def create_lean_package(name: str, base_dir: str = ".", dependencies: list[str] | None = None) -> str:
    """Scaffold a minimal Lean 4 project directory.

    Creates ``lean-toolchain``, ``lakefile.lean`` and a starter source file.
    Note: this does not invoke ``lake``; it only writes project files.
    """
    import textwrap
    fm = FileManager(base_dir)
    pkg_dir = name
    fm.write_text(f"{pkg_dir}/lean-toolchain", "leanprover/lean4:v4.14.0\n")
    deps = dependencies or ["Mathlib"]
    requires = "\n".join(f'  require {d} from git "https://github.com/leanprover/{d}.git"' if d == "Mathlib" else f'  require {d}' for d in deps)
    lakefile = textwrap.dedent(f'''\
        import Lake
        Lake.loadLakeFile ({{ }} : Lake.Configuration)
        package "{name}" where
        {requires}
    ''')
    fm.write_text(f"{pkg_dir}/lakefile.lean", lakefile)
    src = textwrap.dedent(f'''\
        -- {name}: generated by Mathematics AI
        def hello : String := "Mathematics AI Lean package: {name}"
        #eval hello
    ''')
    fm.write_text(f"{pkg_dir}/src/{name}/Basic.lean", src)
    return str((Path(base_dir) / pkg_dir).resolve())


def save_matrix_dataset(name: str, matrix: list[list[Any]], base_dir: str = ".") -> str:
    """Save a numeric matrix as JSON (for algebraic-structure datasets)."""
    fm = FileManager(base_dir)
    return fm.write_json(f"matrices/{name}.json", {"shape": [len(matrix), len(matrix[0]) if matrix else 0], "data": matrix})


__all__ = ["FileManager", "create_lean_package", "save_matrix_dataset"]
