"""SDS generator — Safety Data Sheets and exposure limits (PEL/TLV)."""


class SDSGenerator:
    """Generate a summary Safety Data Sheet structure."""

    EXPOSURE_LIMITS = {
        "toluene": {"PEL_ppm": 200, "TLV_ppm": 20},
        "dichloromethane": {"PEL_ppm": 25, "TLV_ppm": 50},
        "acetone": {"PEL_ppm": 1000, "TLV_ppm": 500},
        "ethanol": {"PEL_ppm": 1000, "TLV_ppm": 1000},
        "isopropanol": {"PEL_ppm": 400, "TLV_ppm": 200},
        "hexanes": {"PEL_ppm": 500, "TLV_ppm": 50},
        "formaldehyde": {"PEL_ppm": 0.75, "TLV_ppm": 0.1},
        "hydrogen sulfide": {"PEL_ppm": 20, "TLV_ppm": 1},
    }

    def generate(self, chemical, properties=None):
        properties = properties or {}
        limits = self.EXPOSURE_LIMITS.get(chemical.lower(), {})
        return {
            "section_1_identification": {"product": chemical},
            "section_2_hazards": properties.get("ghs", "see GHS classifier"),
            "section_3_composition": properties.get("composition", "not specified"),
            "section_4_first_aid": {
                "inhalation": "Move to fresh air; seek medical attention.",
                "skin": "Remove contaminated clothing; rinse skin with water.",
                "eyes": "Rinse cautiously with water for 15 min; get medical help.",
                "ingestion": "Do not induce vomiting; seek medical attention.",
            },
            "section_5_fire_fighting": properties.get("fire", "Use appropriate extinguishing media."),
            "section_6_accidental_release": "Contain, absorb with inert material, ventilate.",
            "section_7_handling_storage": "Store in cool, ventilated area; keep container closed.",
            "section_8_exposure_controls": {"PEL_ppm": limits.get("PEL_ppm"),
                                            "TLV_ppm": limits.get("TLV_ppm")},
            "section_9_physical_properties": properties.get("physical", {}),
            "section_10_stability": "Stable under recommended conditions.",
            "section_11_toxicology": properties.get("tox", "consult full SDS"),
            "section_12_ecology": properties.get("ecotox", "avoid release to environment"),
            "section_13_disposal": "Dispose per local regulations; see waste_disposal module.",
            "section_14_transport": properties.get("transport", "consult DOT/IATA"),
            "section_15_regulatory": "Consult applicable regulations.",
            "section_16_other": "Generated by Chemistry AI SDS module.",
        }

    def exposure_limits(self, chemical):
        return self.EXPOSURE_LIMITS.get(chemical.lower(), {"note": "no data"})
